#!/usr/bin/env python3
"""
Integration tests for the ASAM vocabularies derived into ``imports/``.

``imports/opendrive/`` and ``imports/openscenario/`` are byte-for-byte copies of artifacts
produced in the ``asam-openx-standards`` submodule (see ``omb/utils/asam_imports.py``). These
tests cover the three ways that arrangement can silently break:

1. **Drift** - the copy no longer matches the submodule, because someone edited it by hand or
   bumped the submodule without re-deriving.
2. **Unregistered** - the files are present but not in ``imports/catalog-v001.xml``, so nothing
   resolves them and they are dead weight.
3. **Incoherent** - the SHACL shapes target classes the OWL ontology does not define, which is
   the same defect ``check-artifact-coherence`` guards against for this repository's own
   domains. The ASAM pair is generated by an external toolchain, so it gets the same check
   rather than being trusted.

Tests 2 and 3 need the submodule and so follow the same rule as the enum drift guard: skip
locally, where a missing checkout is legitimate, but fail where the sources are guaranteed - the
``Pinned Standards Drift`` job, which initialises the submodule and sets
``OMB_REQUIRE_PINNED_SOURCES=1``. A drift guard that quietly stops running is worse than none.
Tests 1 and 4 need no submodule at all: the derived copies are committed.
"""

import os
from pathlib import Path

import pytest

from omb.core.constants import ASAM_SUBMODULE_HINT
from omb.utils.asam_imports import ASAM_IMPORTS, check, submodule_root
from omb.utils.registry_resolver import RegistryResolver
from omb.validators.coherence_validator import (
    extract_ontology_classes,
    extract_shacl_classes_from_file,
)

ROOT_DIR = Path(__file__).parent.parent.parent.resolve()
IMPORTS_DIR = ROOT_DIR / "imports"

#: Ontology IRI of each derived vocabulary, as the ASAM UML model declares it. Written out
#: rather than read from the file so that a change to the IRI is a test failure: the IRI is the
#: contract between the catalog, the shapes and any instance data referring to these classes.
ASAM_ONTOLOGY_IRIS = {
    "opendrive": "http://code.asam.net/simulation/standard/opendrive",
    "openscenario": "http://code.asam.net/simulation/standard/openscenario",
}


def _require_submodule() -> None:
    """Skip locally when the submodule is absent; fail where it is guaranteed."""
    if submodule_root(ROOT_DIR).is_dir():
        return
    what = "the pinned ASAM standards submodule"
    if os.environ.get("OMB_REQUIRE_PINNED_SOURCES"):
        raise AssertionError(
            f"{what} is missing while OMB_REQUIRE_PINNED_SOURCES is set. "
            f"{ASAM_SUBMODULE_HINT}"
        )
    pytest.skip(f"{what} is not checked out. {ASAM_SUBMODULE_HINT}")


@pytest.fixture(scope="module")
def resolver() -> RegistryResolver:
    return RegistryResolver(ROOT_DIR)


@pytest.mark.parametrize("vocabulary", sorted(ASAM_IMPORTS))
def test_asam_import_bundle_is_complete(vocabulary: str):
    """Each derived directory holds the ontology, the shapes and at least one schema."""
    directory = IMPORTS_DIR / vocabulary
    assert (directory / f"{vocabulary}.owl.ttl").exists()
    assert (directory / f"{vocabulary}.shacl.ttl").exists()
    assert sorted((directory / "schema").glob("*.xsd")), (
        "no normative schema was derived"
    )


def test_asam_imports_match_the_submodule_byte_for_byte():
    """The derived copy is identical to its source, including line endings.

    This is the whole basis for treating ``imports/`` as derived rather than maintained: if it
    can differ, it is a second copy that has to be reviewed on its own.
    """
    _require_submodule()
    differences = check(ROOT_DIR)
    assert differences == [], (
        "imports/ no longer matches the ASAM standards submodule:\n  "
        + "\n  ".join(differences)
        + "\nRun 'just asam-imports' then 'just registry-update'."
    )


@pytest.mark.parametrize("vocabulary", sorted(ASAM_IMPORTS))
def test_asam_ontology_resolves_through_the_imports_catalog(
    vocabulary: str, resolver: RegistryResolver
):
    """The ontology IRI maps to the derived file, so imports resolve offline."""
    iri = ASAM_ONTOLOGY_IRIS[vocabulary]
    paths = resolver.get_base_ontology_paths_for_iris({iri})
    expected = f"imports/{vocabulary}/{vocabulary}.owl.ttl"
    assert expected in paths, f"{iri} does not resolve to {expected}; got {paths}"


@pytest.mark.parametrize("vocabulary", sorted(ASAM_IMPORTS))
def test_asam_shapes_are_discovered_for_their_namespace(
    vocabulary: str, resolver: RegistryResolver
):
    """Data in an ASAM namespace pulls in the ASAM shapes.

    ``RegistryResolver`` has read shapes from the imports catalog since before any import
    shipped them; this asserts the generator now writes the entries it reads, which is what
    makes the ASAM shapes participate in validation at all.
    """
    iri = ASAM_ONTOLOGY_IRIS[vocabulary]
    paths = resolver.get_import_shacl_paths_for_iris({f"{iri}#SomeClass"})
    expected = f"imports/{vocabulary}/{vocabulary}.shacl.ttl"
    assert expected in paths, f"shapes for {iri} were not discovered; got {paths}"


@pytest.mark.parametrize("vocabulary", sorted(ASAM_IMPORTS))
def test_asam_shacl_targets_are_defined_in_the_ontology(vocabulary: str):
    """Every class the shapes target is declared by the ontology they were derived from.

    This is ``check-artifact-coherence`` applied to the ASAM pair, using the same extractors.
    A missing target class here would mean the OWL→SHACL stage produced shapes for classes the
    OWL stage dropped - exactly the enumeration-dropping regression the submodule's pipeline
    documents - and no amount of instance data would reveal it, because a shape whose target
    class is never instantiated simply never fires.
    """
    directory = IMPORTS_DIR / vocabulary
    ontology_classes = extract_ontology_classes(
        str(directory / f"{vocabulary}.owl.ttl")
    )
    shacl_classes = extract_shacl_classes_from_file(
        str(directory / f"{vocabulary}.shacl.ttl")
    )

    assert shacl_classes, (
        "no target classes found in the shapes; the check would be vacuous"
    )
    missing = shacl_classes - ontology_classes
    assert not missing, (
        f"{len(missing)} SHACL target class(es) are not defined in {vocabulary}.owl.ttl: "
        + ", ".join(sorted(missing)[:10])
    )
